inherit_gem:
  rubocop-zuno:
    - rspec.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-zuno

plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - gemfiles/**/*
